# This is an example .meta-cnc.yaml file. This will allow Panhandler to consume this terraform project

# this is the name of this skillet, should be unique within a given repository
name: alicloud_lb_sandwich

# label should be a human readable label that conveys what this skillet will do
label: Alicloud LB Sandwich Step 1 Infrasturture Build

# description is a longer more informative version of a label
description: This skillet deploys the Alicloud LB Sandwich environment - two VM-Series, two web servers, one external LB and one internal LB

# type instructs Panhandler how to consume this skillet
type: terraform

# extends allows you to include other skillets along with this one
extends:

# labels allow extensible configuration options per skillet type. For example, lables can be used to
# group multiple skillets of the same type (pan-os skillets labeled as version: 9.0 for example)
labels:
  collection:
    - YKB Skillets
  terraform_provider: alicloud


# Variables will be presented to the user via the Panhandler GUI. These values will then be passed to
# the terraform binary as '--var' options, thus overriding any tfvars entries.
# Variable names MUST match the names of the defined terraform variables
variables:
  - name: access_key
    description: Alicloud Access Key
    default: access_key
    type_hint: text
  - name: secret_key
    description: Alicloud Secret Key
    default:
    type_hint: password
  - name: fw-region
    description: Alicloud Region
    default: ap-southeast-1
    type_hint: text

